interface Language {
  value: string;
  code?: string;
}

const languages: Language[] = [
  { value: 'Afrikaans' },
  { value: 'Albanian',  code: 'alb' },
  { value: 'Amharic' },
  { value: 'Arabic',  code: 'ar' },
  { value: 'Armenian',  code: 'arm' },
  { value: 'Azerbaijani' },
  { value: 'Basque' },
  { value: 'Belarusian' },
  { value: 'Bengali' },
  { value: 'Bosnian' },
  { value: 'Bulgarian',  code: 'bul' },
  { value: 'Catalan' },
  { value: 'Cebuano' },
  { value: 'Chichewa' },
  { value: 'Chinese (Simplified)' },
  { value: 'Chinese (Traditional)' },
  { value: 'Corsican' },
  { value: 'Croatian' },
  { value: 'Czech' },
  { value: 'Danish' },
  { value: 'Dutch' },
  { value: 'English', code: 'en' },
  { value: 'Esperanto' },
  { value: 'Estonian' },
  { value: 'Filipino' },
  { value: 'Finnish' },
  { value: 'French', code: 'fr' },
  { value: 'Frisian' },
  { value: 'Galician' },
  { value: 'Georgian' },
  { value: 'German' },
  { value: 'Greek', code: 'el' },
  { value: 'Gujarati' },
  { value: 'Haitian Creole' },
  { value: 'Hausa' },
  { value: 'Hawaiian' },
  { value: 'Hebrew' },
  { value: 'Hindi' },
  { value: 'Hmong' },
  { value: 'Hungarian' },
  { value: 'Icelandic' },
  { value: 'Igbo' },
  { value: 'Indonesian' },
  { value: 'Irish' },
  { value: 'Italian' },
  { value: 'Japanese' },
  { value: 'Javanese' },
  { value: 'Kannada' },
  { value: 'Kazakh' },
  { value: 'Khmer' },
  { value: 'Kinyarwanda' },
  { value: 'Korean' },
  { value: 'Kurdish (Kurmanji)' },
  { value: 'Kyrgyz' },
  { value: 'Lao' },
  { value: 'Latin' },
  { value: 'Latvian' },
  { value: 'Lithuanian' },
  { value: 'Luxembourgish' },
  { value: 'Macedonian' },
  { value: 'Malagasy' },
  { value: 'Malay' },
  { value: 'Malayalam' },
  { value: 'Maltese' },
  { value: 'Maori' },
  { value: 'Marathi' },
  { value: 'Mongolian' },
  { value: 'Myanmar (Burmese)' },
  { value: 'Nepali' },
  { value: 'Norwegian' },
  { value: 'Odia (Oriya)' },
  { value: 'Pashto' },
  { value: 'Persian' },
  { value: 'Polish' },
  { value: 'Portuguese' },
  { value: 'Punjabi'}
]

export { languages, Language};
